# Generated by Django 6.1 on 2026-09-24 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_encuestas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='ubicacion',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
        migrations.DeleteModel(
            name='Ubicacion',
        ),
    ]
